name: Validate & Release

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: ls -la

  release:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: codfish/semantic-release-action@v1
        if: github.ref == 'refs/heads/master'
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo $RELEASE_VERSION
          echo $RELEASE_MAJOR
          echo $RELEASE_MINOR
          echo $RELEASE_PATCH
          echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
